---
- name: "Creating Ec2 Instance Using Ansible"
  hosts: localhost
  vars:

    keypair_name: "ansible"
    access_key: "AKIATXRAUEYFBD3FDOXY"
    secret_key: "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"
    region: "ap-south-1"
    security_group1: "ansible-remote"
    security_group2 : "ansible-webserver"
  tasks:
    
    - name: "Aws - Creating Ssh KeyPair"
      ec2_key:
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        region: "{{ region }}"
        name: "{{ keypair_name }}"
        state: present
      register: keypair_content
        
    - name: "Aws - Saving Private Key Content"
      when: keypair_content.changed == true
      copy:
        content: "{{ keypair_content.key.private_key }}"
        dest: "{{ keypair_name }}.pem"
        mode: 0400
            
    -  name: "Aws - Creating Security Group {{ security_group1 }}"
       ec2_group:
         aws_access_key: "{{ access_key }}"
         aws_secret_key: "{{ secret_key }}"
         region: "{{ region }}"
         name: "{{ security_group1 }}"
         description: "Allows Only 22 Conntenction"
         rules:
           - proto: tcp
             from_port: 22
             to_port: 22
             cidr_ip:
               - 0.0.0.0/0
             cidr_ipv6:
               - ::/0
         tags:
            Name: "{{ security_group1 }}"
       register: security_group1_status       
                
    -  name: "Aws - Creating Security Group {{ security_group2  }}"
       ec2_group:
         aws_access_key: "{{ access_key }}"
         aws_secret_key: "{{ secret_key }}"
         region: "{{ region }}"
         name: "{{ security_group2  }}"
         description: "Allows Only 80,443 Conntenction"
         rules:
           - proto: tcp
             from_port: 80
             to_port: 80
             cidr_ip:
               - 0.0.0.0/0
             cidr_ipv6:
               - ::/0
                    
           - proto: tcp
             from_port: 443
             to_port: 443
             cidr_ip:
               - 0.0.0.0/0
             cidr_ipv6:
               - ::/0
         tags:
            Name: "{{ security_group2  }}"
                
       register: security_group2_status 
                
                
    - name: "Aws - Creating Ec2 Instance"
      ec2:
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        region: "{{ region }}"
        key_name: "{{ keypair_name }}"
        instance_type: "t2.micro"
        image: "ami-052cef05d01020f1d"
        group_id:
          - "{{ security_group1_status.group_id }}"
          - "{{ security_group2_status.group_id }}"
        instance_tags:
            Name: "webserver"
        count_tag:
          Name: "webserver"
        exact_count: 3
        wait: true
      register: ec2_status  
        
    - name: "Creating Dynamic Inventory"
      add_host:
        name: "{{ item.public_ip }}"
        groups: "webserver"
        ansible_host: "{{ item.public_ip }}"
        ansible_port: 22
        ansible_user: "ec2-user"
        ansible_ssh_private_key_file: "{{ keypair_name }}.pem"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      with_items:
        - "{{ ec2_status.tagged_instances }}"
        
    
    - name: "Wait 200 seconds before checking SSH connections"
      wait_for_connection:
        timeout: 60
        

- name: "Installing Apache Webserver23"
  become: true
  hosts: webserver
  tasks:
    
    - name: "Installing Apache Webserver2"
      yum:
        name: httpd
        state: present
            
            
    - name: "Creating index.html"
      copy:
        content: "<center><h1>{{ ansible_fqdn }} </h1></center>"
        dest: /var/www/html/index.html

            
    - name: "Restarting/Enabling httpd"
      service:
        name: httpd
        state: restarted
        enabled: true